# Generated by Django 3.2.16 on 2023-02-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_Assistant',
            field=models.BooleanField(default=False),
        ),
    ]
