# Generated by Django 3.2.8 on 2023-04-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='newuser',
            name='role',
            field=models.CharField(blank=True, choices=[('club_manager', 'club_manager'), ('club_coach', 'club_coach'), ('regular_member', 'regular_member')], default='others', max_length=20),
        ),
    ]
