# Generated by Django 3.2.8 on 2023-04-24 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230424_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='role',
        ),
    ]
