# Generated by Django 3.2.16 on 2023-02-14 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_is_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='flag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
