# Generated by Django 3.2.16 on 2023-02-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230214_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='sections',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='newuser',
            name='university',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
