# Generated by Django 3.2.9 on 2023-03-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230223_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
