# Generated by Django 3.2.9 on 2023-03-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newuser_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_activeChat',
            field=models.BooleanField(default=False),
        ),
    ]
