# Generated by Django 3.2.9 on 2023-03-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_newuser_is_activechat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='is_activeChat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
