# Generated by Django 3.2.16 on 2023-02-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='name2',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
