# Generated by Django 3.2.16 on 2023-02-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat2', '0002_room_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='name2',
        ),
    ]
