# Generated by Django 3.2.8 on 2023-05-05 22:19

import chat3.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chat3.models.uplodChat)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at2', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion_topic', models.TextField(blank=True)),
                ('description_for_the_theme', models.TextField(blank=True)),
                ('voting_questions', models.TextField(blank=True)),
                ('files', models.TextField(blank=True)),
                ('list_of_people_who_vote', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chat3.models.uplodvote)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('Chat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Chat_id_in_vote', to='chat3.chat')),
                ('user_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=chat3.models.uplodRoom)),
                ('administrator', models.ManyToManyField(blank=True, related_name='administrator', to=settings.AUTH_USER_MODEL)),
                ('club_coaches', models.ManyToManyField(blank=True, related_name='club_coaches', to=settings.AUTH_USER_MODEL)),
                ('club_leader', models.ManyToManyField(blank=True, related_name='club_leader', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(blank=True, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification', to='chat3.chat')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id_Notification', to='chat3.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creater_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_id', to='chat3.room'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='user_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
