# Generated by Django 3.2.9 on 2023-03-25 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room_id',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='room_id_Notification', to='chat3.room'),
            preserve_default=False,
        ),
    ]
