# Generated by Django 3.2.8 on 2023-05-07 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat3', '0002_auto_20230505_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='list_of_people_who_vote',
        ),
        migrations.AddField(
            model_name='voting_questions',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting_questions',
            name='list_of_people_who_vote',
            field=models.ManyToManyField(blank=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='list_of_people_who_vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_question', models.TextField()),
                ('list_of_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_people', to='chat3.vote')),
            ],
        ),
    ]
