# Generated by Django 3.2.8 on 2023-05-08 19:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat3', '0004_auto_20230508_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting_questions',
            name='list_of_people_who_vote',
            field=models.ManyToManyField(blank=True, null=True, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
