# Generated by Django 3.2.9 on 2023-03-26 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat3', '0004_chat_user_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user_to',
        ),
        migrations.AddField(
            model_name='chat',
            name='user_to',
            field=models.ManyToManyField(related_name='user_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
