# Generated by Django 3.2.8 on 2023-05-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat3', '0005_alter_voting_questions_list_of_people_who_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='Chat_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='voting_questions',
        ),
        migrations.AddField(
            model_name='vote',
            name='voting_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='votes', to='chat3.Voting_Questions'),
        ),
    ]
