# Generated by Django 3.2.16 on 2023-02-14 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import university.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='sections_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=university.models.uplodeimgeuniversity)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by_sections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='university_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('link', models.TextField(blank=True, max_length=1000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=university.models.uplodeimgeuniversity)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_by_university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_university', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='universityVideoArry_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_universityVideoArry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_universityVideoArry', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
        migrations.CreateModel(
            name='universityPhotoArry_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=university.models.uplodeimgeuniversity)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_universityPhotoArry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_universityPhotoArry', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
        migrations.CreateModel(
            name='universityDescription_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_universityDescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_universityDescription', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
        migrations.CreateModel(
            name='sectionsVideoArry_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('link', models.CharField(max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_sectionsVideoArry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_sectionsVideoArry', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.sections_models')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
        migrations.CreateModel(
            name='sectionsPhotoArry_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=university.models.uplodeimgeuniversity)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_sectionsPhotoArry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_sectionsPhotoArry', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.sections_models')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
        migrations.AddField(
            model_name='sections_models',
            name='university',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models'),
        ),
        migrations.CreateModel(
            name='FormAplctionUser_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_UserAll', models.CharField(max_length=150, null=True)),
                ('phone', models.CharField(max_length=150, null=True)),
                ('famile_Name_User', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=university.models.uplodephoto_Pass)),
                ('Acca', models.ImageField(blank=True, null=True, upload_to=university.models.uplodephoto_Acca)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_FormAplctionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_FormAplctionUser', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.sections_models')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
    ]
