# Generated by Django 3.2.16 on 2023-02-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import university.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Tasks', models.CharField(max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=university.models.uplodephoto_Pass)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_Tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_Tasks', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.sections_models')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
    ]
