# Generated by Django 3.2.16 on 2023-02-14 21:04

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_tasks_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_models',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formaplctionuser_models',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=university.models.uplodephoto_Pass),
        ),
    ]
