# Generated by Django 3.2.16 on 2023-02-15 00:10

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20230214_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formaplctionuser_models',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=university.models.uplodephoto_Pass),
        ),
    ]
