# Generated by Django 3.2.16 on 2023-02-15 02:14

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_alter_formaplctionuser_models_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_models',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='formaplctionuser_models',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=university.models.uplodephoto_Pass),
        ),
    ]
