# Generated by Django 3.2.16 on 2023-02-15 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0005_auto_20230215_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks_models',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tasks_models',
            name='price',
        ),
        migrations.CreateModel(
            name='Package_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Package', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_Package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_Package', to=settings.AUTH_USER_MODEL)),
                ('sections', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.sections_models')),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
        migrations.AddField(
            model_name='tasks_models',
            name='Package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.package_models'),
        ),
    ]
