# Generated by Django 3.2.16 on 2023-02-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20230215_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_models',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
