# Generated by Django 3.2.16 on 2023-02-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0007_tasks_models_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTrns_Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneTrns', models.DecimalField(decimal_places=1, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by_PhoneTrns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_PhoneTrns', to=settings.AUTH_USER_MODEL)),
                ('university', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='university.university_models')),
            ],
        ),
    ]
