# Generated by Django 3.2.16 on 2023-02-20 08:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_phonetrns_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetrns_models',
            name='PhoneTrns',
        ),
        migrations.AddField(
            model_name='phonetrns_models',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter phone number in international format', max_length=128, null=True, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
