# Generated by Django 3.2.16 on 2023-02-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20230220_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonetrns_models',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='phonetrns_models',
            name='PhoneTrns',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
