# Generated by Django 3.2.16 on 2023-02-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_alter_phonetrns_models_phonetrns'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonetrns_models',
            name='Name_Compony',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
