# Generated by Django 3.2.16 on 2023-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_phonetrns_models_name_compony'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetrns_models',
            name='Name_Compony',
            field=models.CharField(choices=[('vodafone', 'Vodafone'), ('orange', 'Orange'), ('etisalat', 'Etisalat')], default='male', max_length=20),
        ),
    ]
