# Generated by Django 3.2.16 on 2023-02-20 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0019_alter_paymentconfirmation_models_apathy'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation_models',
            name='Assistsnt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Assistsnt', to='users.newuser'),
            preserve_default=False,
        ),
    ]
