# Generated by Django 3.2.16 on 2023-02-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0020_paymentconfirmation_models_assistsnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmation_models',
            name='created_at2',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
