# Generated by Django 3.2.16 on 2023-02-23 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0021_paymentconfirmation_models_created_at2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentconfirmation_models',
            old_name='created_at',
            new_name='created_at_py',
        ),
        migrations.RenameField(
            model_name='paymentconfirmation_models',
            old_name='created_at2',
            new_name='created_at_py2',
        ),
    ]
