# Generated by Django 3.2.9 on 2023-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0023_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_models',
            name='description',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='sections_models',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='sections_models',
            name='link',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='sectionsvideoarry_models',
            name='link',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='tasks_models',
            name='description',
            field=models.TextField(blank=True, max_length=700),
        ),
        migrations.AlterField(
            model_name='university_models',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='university_models',
            name='link',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='universitydescription_models',
            name='description',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='universitydescription_models',
            name='link',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='universityvideoarry_models',
            name='link',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
