# Generated by Django 3.2.9 on 2023-03-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0024_auto_20230305_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
